language: python
sudo: required
python:
   - 3.6

before_install:
    - set -e  # fail on any error
    - sudo apt-get update -q

install:
   - pip install --upgrade pip
   - pip install --progress-bar off -r requirements.txt
   - pip install --progress-bar off --editable .
   - pip install --progress-bar off nose

script:
#   - nosetests tests -s
